### ISSUE TITLE
different embedding must be used.

### ISSUE THREAD

**Issue by bicepjai** [airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier#13]
seems like the same embeddings are used for for all the right context, left context and the word embedding. If you look at the training section its stated clearly that these are different parameters

so it should probably something like
```

document      = Input(shape=(None,), dtype = "int32")

document_embedding       = Embedding(vocab_size, WORD_EMB_SIZE, weights=[initial_embeddings],
                                     input_length=DOC_SEQ_LEN, trainable=True)(document)
left_context_embedding   = Embedding(vocab_size, WORD_EMB_SIZE, weights=[left_context_embeddings],
                                     input_length=DOC_SEQ_LEN, trainable=True)(document)
right_context_embedding  = Embedding(vocab_size, WORD_EMB_SIZE, weights=[right_context_embeddings],
                                     input_length=DOC_SEQ_LEN, trainable=True)(document)
```

**Comment by airalcorn2** [comment]
I'm not sure where in the paper you're referring to? The same embedding function, `e`, is used in equations  (1), (2), and (3) and there is only a single embedding matrix, `E`, mentioned in "**Training Network parameters**".

**Comment by bicepjai** [comment]
I was referring to the context vectors c_l and c_r in equations (1) and (2)
e refers to word embeddings and c_l/c_r refers to their own embedding and are not related to e. Thats what i was getting from the equation (8) from [here](https://www.aaai.org/ocs/index.php/AAAI/AAAI15/paper/view/9745/9552)

**Comment by airalcorn2** [comment]
Please use the equations in the code as a reference. The left and right context vectors are defined [here](https://github.com/airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier/blob/master/recurrent_convolutional_keras.py#L38) and [here](https://github.com/airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier/blob/master/recurrent_convolutional_keras.py#L39).

**Comment by bicepjai** [comment]
code for the the equations (1) (2) (3) and (8)
suggestions/criticism are welcome

```
document       = Input(shape=(None,), dtype = "int32")
left_context   = Input(shape=(None,), dtype = "int32")
right_context  = Input(shape=(None,), dtype = "int32")

document_embedding       = Embedding(vocab_size, WORD_EMB_SIZE, weights=[initial_embeddings],
                                     input_length=DOC_SEQ_LEN, trainable=True)(document)
left_context_embedding   = Embedding(vocab_size, WORD_EMB_SIZE, weights=[left_context_embeddings],
                                     input_length=DOC_SEQ_LEN, trainable=True)(left_context)
right_context_embedding  = Embedding(vocab_size, WORD_EMB_SIZE, weights=[right_context_embeddings],
                                     input_length=DOC_SEQ_LEN, trainable=True)(right_context)

forward_rnn     = LSTM(100, return_sequences = True)(left_context_embedding)
backward_rnn    = LSTM(100, return_sequences = True, go_backwards = True)(right_context_embedding)
recurrent_layer = concatenate([forward_rnn, document_embedding, backward_rnn], axis = 2)

latent_semantic_tensor = TimeDistributed(Dense(200, activation = "tanh"))(recurrent_layer)
maxpool_rcnn = Lambda(lambda x: backend.max(x, axis = 1))(latent_semantic_tensor)
output_layer = Dense(9, activation = "softmax")(maxpool_rcnn)

model = Model(inputs = [left_context, document, right_context], outputs=[output_layer])
```

**Comment by airalcorn2** [comment]
Your code is not correct. As I mentioned before, the paper uses the same embedding matrix to embed words for the left and right contexts. The `Embedding` layer in my code takes a sequence of integers (corresponding to tokens) and converts it to a sequence of word vectors. Alternative names for `doc_embedding`, `l_embedding`, and `r_embedding` could be: `doc_word_embeddings`, `l_word_embeddings`, and `r_word_embeddings`.

**Comment by bicepjai** [comment]
That was my first hypothesis, tried to collect evidence against it and failed :)
Its not mentioned in the paper clearly (may be its obvious), i thought in the name of new model, they try different things. since different variables were used i decided they should be different.
Thanks for clarifying @airalcorn2
