### ISSUE TITLE
Which part represents the Convolutional layer？

### ISSUE THREAD

**Issue by fuhailin** [airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier#16]
Which part represent the Convolutional layer in that code？Dense, Input, Lambda, LSTM, TimeDistributed layers used in that code，and Which part represent the Convolutional layer？

**Comment by airalcorn2** [comment]
@fuhailin - https://github.com/airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier/blob/master/recurrent_convolutional_keras.py#L42.
