### ISSUE TITLE
I have one question. When you get context right, you reverse the input sequences, but you don't reverse the output sequences. I think the output seqences should be reversed.Becaues the LSTM api just reverse the input! thanks!

### ISSUE THREAD

**Issue by JepsonWong** [airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier#17]
https://github.com/airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier/blob/2c4d87d35c99a03a20840acf85ba6583b1340fd4/recurrent_convolutional_keras.py#L39

**Comment by airalcorn2** [comment]
Interestingly, I don't think this bug actually affected the model's performance in any way because of the max-pooling.
