### ISSUE TITLE
does your code also support label data?

### ISSUE THREAD

**Issue by GaryHaHaHa** [airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier#18]
Hello!
your code is really perfect,but it seems like your project doen't support label text Classification,so i wonder how can I modify your code to support the supervised classfication?
thx!

**Comment by airalcorn2** [comment]
You need to convert your labels to one-hot encodings for Keras. See "Encode The Output Variable" [here](https://machinelearningmastery.com/multi-class-classification-tutorial-keras-deep-learning-library/) for an example.

**Comment by GaryHaHaHa** [comment]
Do you mean I should use one-hot encodings to replace Gensim which is used in your codes?

**Comment by GaryHaHaHa** [comment]
Perhaps I didn't make myself clearly,I want to train a set of text data where every piece of text data has its label.For example: label a:"hello, how are you",label  b : "I am fine ,thanks you" ,label c :“thx”.

**Comment by airalcorn2** [comment]
@GaryHaHaHa - it sounds like you might be new to natural language processing. I have links to some helpful NLP resources in [my data science curriculum](https://github.com/airalcorn2/Michael-s-Data-Science-Curriculum#Natural-Language-Processing).
