### ISSUE TITLE
Where is the Convolutional layer？

### ISSUE THREAD

**Issue by CXX1113** [airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier#20]
I saw that the same issues as me were raised, but I couldn't read the author's answer.

**Comment by airalcorn2** [comment]
@alanlisten - `TimeDistributed(Dense(hidden_dim_2, activation = "tanh")` is the same thing as `Conv1D(hidden_dim_2, kernel_size = 1, activation = "tanh")`. [I've updated the code to make it more obvious.](https://github.com/airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier/commit/cc99fd8c2cf9189ad3c4074ef652f4ec4e75d6c0)
