### ISSUE TITLE
Getting error while running word2vec.gensi

### ISSUE THREAD

**Issue by abhi5485** [airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier#21]
hello,
I've tried to run your code but getting error as 
FileNotFoundError: [Errno 2] No such file or directory: 'word2vec.gensim'

while running word2vec = gensim.models.Word2Vec.load("word2vec.gensim")

please help me rectify this error

**Comment by airalcorn2** [comment]
You need to create/find an embeddings file. See [here](https://radimrehurek.com/gensim/models/word2vec.html).
