### ISSUE TITLE
Question about equal(1) and equal(2)

### ISSUE THREAD

**Issue by Jingyilang** [airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier#22]
Thanks for your code! However I have a question about the implementtation of equal(1) abd equal(2). The means of equal(1) and equal(2) is just a original RNN？ And you instead it with LSTM?

**Comment by airalcorn2** [comment]
[Correct.](https://github.com/airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier/blob/master/recurrent_convolutional_keras.py#L37)
