### ISSUE TITLE
TypeError: maketrans() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by prernakhurana2** [airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier#5]
When running the code , I get this error:
TypeError: maketrans() takes exactly 2 arguments (1 given)

at this line of code:
text = text.strip().lower().translate(string.maketrans({key: " {0} ".format(key) for key in string.punctuation}))

How to resolve this ?

**Comment by airalcorn2** [comment]
Use the [original code](https://github.com/guodao/Recurrent-Convolutional-Neural-Network-Text-Classifier/blob/master/recurrent_convolutional_keras.py#L53) and Python 3.
