### ISSUE TITLE
training with multiple documents at once

### ISSUE THREAD

**Issue by jhoh10** [airalcorn2/Recurrent-Convolutional-Neural-Network-Text-Classifier#9]
Thanks you for posting this code on github. It is functional for me as is, but I was looking into performing batch training with this network. Do you know how to approach this if the documents being classified have variable lengths? I was considering padding the inputs to the same size, but since my documents have huge variations in length, many documents would be heavily padded. I am looking for a better approach.

**Comment by airalcorn2** [comment]
Unfortunately, your only two options are to either pad your data or process the variable length documents one at a time.
